version: '3.7'

services:
  wp-database:  
    image: mariadb:10.6.4-focal
    container_name: wp-database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: my_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wordpress-network

  phpmyadmin:
    depends_on:
      - wp-database
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      PMA_HOST: wp-database
      MYSQL_ROOT_PASSWORD: my_root_password
    networks:
      - wordpress-network

  wordpress:
    depends_on:
      - wp-database
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: wp-database:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
    volumes:
      - wp-data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    networks:
      - wordpress-network

  codecept:
    depends_on:
      - wordpress
      - chrome
    image: codeception/codeception:5.1.2
    container_name: codeception
    volumes:
      - test-data:/project
      - .:/project/:rw
    networks:
      - wordpress-network

  chrome:
    image: selenium/standalone-chrome:127.0-chromedriver-127.0
    container_name: selenium-chrome
    ports:
      - "7900:7900"
      - "4444:4444"
    shm_size: 2g
    networks:
      - wordpress-network

volumes:
  db-data:
  test-data:
  wp-data:

networks:
  wordpress-network:
    driver: bridge
